### ISSUE TITLE
How to grab traffic in shadow

### ISSUE THREAD

**Issue by gmhXing** [shadow/shadow-plugin-tor#109]
I built a private Tor network using Shadow on the virtual machine, and it has been successfully tested.But I want to use the traffic to do further research.How can I capture traffic from the Shadow? Please help me.Thanks!

**Comment by robgjansen** [comment]
Sorry - this question got overlooked!

You can capture packets being sent between hosts in the simulation by modifying the config.xml file, and adding the attributes "logpcap=true" and "pcapdir=packetinfo" to the "host" element. For example:

```
<host id="client1" logpcap="true" pcapdir="packetinfo" ...>
```

Then make sure the "packetinfo" directory exists, and create it if it
doesn't.

After running the experiment, you should be able to view the pcap output files
that get placed in the packetinfo directory with tools like wireshark. The view in wireshark will be a bit different than you are used to, because TCP sequence numbers in Shadow refer to packets rather than bytes.

See [the documentation for the host config](https://github.com/shadow/shadow/blob/dev/docs/3.1-Shadow-Config.md#the-host-element) for more details on the configuration file.
