### ISSUE TITLE
Need to explicitly disable ipv6 on tor @ 0.4.5.7

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow-plugin-tor#120]
(See also https://github.com/shadow/tornettools/issues/9)

Jaym (@frochet:matrix.org) is working with tor-0.4.5.7 and found that it's trying to use ipv6 with the generated configs. They were using shadow-plugin-tor/tools/generate.py.

It looks like the phantom CI has "ORPort 9111 IPv4Only" in its tor configs. Maybe we need to add it here too?

**Comment by robgjansen** [comment]
Please use the main branch of https://github.com/shadow/tornettools/commit/0fd1a85439fc6d5d39ee5f9382855d8871f00a06 or later when generating new Tor networks. It follows Tor's required values for the `ORPort` config:

- For tor v0.4.4.x or earlier, use `ORPort 9000`
- For tor v0.4.5.x or later, use `ORPort 9000 IPv4Only`

I don't plan to offer support for `shadow-plugin-tor/tools/generate.py` anymore since publishing https://github.com/shadow/tornettools.

If using `shadow-plugin-tor/tools/generate.py` now, the workaround is to manually append `IPv4Only` to your ORPort lines in the torrc config files generated by the script.

**Comment by sporksmith** [comment]
Should we delete `shadow-plugin-tor/tools/generate.py`?

**Comment by robgjansen** [comment]
Once we do the Shadow dev->main merge, much of this repository becomes obsolete - we won't actually need it to run Tor simulations anymore. I'm thinking about archiving it, and moving the parts we do want to keep (the preload shim) to a new minimal repo that will be easier to maintain.
