### ISSUE TITLE
Encryption Method Change

### ISSUE THREAD

**Issue by Bazarovay** [shadow/shadow-plugin-tor#40]
Hey, is there a way to change the encryption method and see how it affects the performance of the tor network? 

P.S I see that there is an AES_encrypt method in /src/tor/shadowtor-preload.c, should I be trying to modify it to achieve desired result?

**Comment by robgjansen** [comment]
The functions in `src/tor/shadowtor-preload.c` are meant to skip encryption as an optimization for the simulator. If you wanted to add some kind of operations there you could, but I advise against doing so because your changes may have unintended side-effects.

If you really want to change the Tor encryption method, the best way would be to change the way that Tor does encryption from inside of the Tor code-base, i.e., change Tor to actually do whatever encryption method you want to test. Then just build shadow-tor as usual and the new methods would be invoked.

Hope that helps!
