### ISSUE TITLE
Customizing small tor network

### ISSUE THREAD

**Issue by mfayoub** [shadow/shadow-plugin-tor#51]
I would like to know how to fully customize a Tor network by doing changes to the minimal example. My changes include adding/removing some relays, clients and servers. My main confusion is about two folders.
1) "shadow.data.template", What is this folder for and do I need to add folder if I wanna add new hosts (relays, clients and servers) ?
2) and "conf". I see it has the traffic generators and tor configuration files. But what are the files authen.pw and authen.torrc for ?

**Comment by robgjansen** [comment]
1. `shadow.data.template` is generated by the `generate.py` script. It contains a directory for every relay in the network. Those directories are used as the data directory for the relays. The reason we generate those ahead of an experiment is so that the relay fingerprints are persistent. That way we can add the relay fingerprints into the torrc files to configure some options that are useful for test networks, like which relays get assigned the guard and exit flags.  
If you add new Tor clients into your `shadow.config.xml`, you don't have to add anything into the template dir. If you add relays into your `shadow.config.xml`, you only have to add a new data directory named by the name of the host in the shadow config file in the template directory if you want to assign a guard or exit flag to that relay (which is done in the `conf/tor.authority.torrc` file).

2. These files are used when running the `generate.py` script during the process of generating keys and fingerprints for all of the relays. These files are not used during a simulation.

I think that answers everything, so I'm closing this issue. Cheers!
