### ISSUE TITLE
Can't generate own tor 

### ISSUE THREAD

**Issue by 77ogc** [shadow/shadow-plugin-tor#52]
python ~/shadow-plugin-tor/tools/generate.py --nauths 1 --nrelays 3 --nclients 1 --nservers 3 --fweb 0.90 --fbulk 0.10 --nperf50k 10 --nperf1m 10 --nperf5m 10 ../alexa-top-1000-ips.csv ../2018-03-31-23-00-00-consensus ../server-descriptors-2018-03/ ../extra-infos-2018-03/ ../clients.csv

I get:

Warning: Cant find code for IP '198.41.209.133' Num '3324629381', defaulting to 'US'
Traceback (most recent call last):
  File "/home/ogc/shadow-plugin-tor/tools/generate.py", line 1135, in <module>
    main()
  File "/home/ogc/shadow-plugin-tor/tools/generate.py", line 214, in main
    generate(args)
  File "/home/ogc/shadow-plugin-tor/tools/generate.py", line 334, in generate
    authority = guards_nodes.pop()
IndexError: pop from empty list

Can some one help? THX

**Comment by robgjansen** [comment]
You might need to increase the number of relays (i.e., nrelays) in order for the script to select at least one guard node.

But, if you only want three relays, you should just use the minimal ShadowTor network here:
shadow-plugin-tor/resource/shadowtor-minimal-config.tar.xz

That is set up so things work correctly. You can edit that one by hand if you want to add more nodes.

**Comment by 77ogc** [comment]
Yes, I done all of it.
python ~/shadow-plugin-tor/tools/parse-torperf.py 

python ~/shadow/src/tools/plot-shadow.py --prefix "scheduler" --data min-results/ "minimal" --data priority-results/ "priority" --data torperf-results/ "torperf"

Shouldn't this plot out 3 kinds of line?

Sorry for asking alot. This shall be the last one. Thank you!!

**Comment by robgjansen** [comment]
I assume that "min-results" and "priority-results" are the results from running Shadow experiments. If so, that should give you 2 lines on every graph.

BUT, the "torperf-results" is *not* a Shadow experiment, so that data will not add a line to every plot. It will only add a line to the file download times of 50kb, 1mb, and 5mb plots and also the "first byte" plot.

So, you should get 2 lines on every graph, and 3 lines on the 4 download times graphs. If you are getting less, then either your experiment failed and so there is not actually any data that can be plotted, or the plotting script had an error. (You can check if the data is present by manually inspecting the json files inside the results directories.)

Hope that helps! Keep playing around and you'll keep learning :)

**Comment by 77ogc** [comment]
ohhhh~~Now i know what torperf works!!!!!
Thank u 4 ur help!!!!!!!!!!!!!!!!!!!!!!!!!!
