### ISSUE TITLE
Modify Circuit Selection

### ISSUE THREAD

**Issue by NofelYaseen** [shadow/shadow-plugin-tor#53]
Which files would need updating if I want to change the circuit creation and selection method in Shadow Tor?
In TOR, I used [Stem](https://stem.torproject.org) to modify it. I would like to run system level simulations now.

**Comment by robgjansen** [comment]
This would not be super easy at the moment, because I think you would have to write the Tor control port logic yourself as a c/c++ application. This has been done by some other people too.

There is a plugin that you might consider using as a starting point if you go this route:
https://github.com/shadow/shadow-plugin-extras/tree/master/torcontrol

But I warn that this plugin is not supported, not maintained, and has not been recently tested by me. Still, it might be better than starting from nothing.
