### ISSUE TITLE
Why should I download server-descriptors if I want to generate a new tor network?

### ISSUE THREAD

**Issue by builtinfunction** [shadow/shadow-plugin-tor#65]
I wonder why should I download server-descriptors (or other files from torproject.org) if I want to build my own tor network.
I try to build a tor testing network which should be private and run in a VM. And I may do some changes to the original tor to verify some of my ideas. Shouldn't tor binaries and shadow.config.xml file be enough for building a network?

**Comment by robgjansen** [comment]
The `generate.py` script produces a `shadow.config.xml` file. If you already have one that you are happy with, you don't need to run the script.

The `generate.py` script is used to generate a new `shadow.config.xml` file so that you don't have to manually add relays and other nodes to the `.xml` file yourself. The goal of the script is to produce a testing Tor network that has similar characteristics to the public Tor network. Because the number of relays, the bandwidth capabilities of relays, the Tor client distribution, etc. changes all the time, the `generate.py` script uses the latest data from https://torproject.org to make sure you have a testing Tor network that most closely resembles Tor from a given time period.

The methods applied in the script are described in further detail in the following paper:
```
Methodically Modeling the Tor Network
5th Workshop on Cyber Security Experimentation and Test (CSET 2012)
Rob Jansen, Kevin Bauer, Nick Hopper, and Roger Dingledine 
```
[The paper is available here](https://www.robgjansen.com/publications/tormodel-cset2012.pdf)

**Comment by robgjansen** [comment]
Closing this now, please re-open or comment if the answer is unclear.
