### ISSUE TITLE
Issue with running the Tor plugin.

### ISSUE THREAD

**Issue by RobertRaduta** [shadow/shadow-plugin-tor#81]
When attempting to run the Tor minimal experiment in Shadow, I get the following error:

[_parser_parseContents] g_markup_parse_context_parse: Shadow XML parsing error 5: attribute 'path': '/home/robert/.shadow/shadow-plugin-tor/build/main/src/tor/libshadow-plugin-tor.so' is not a valid path to an existing regular file

I have double-checked and the file is definitely there. Same goes for the preload file. I have also tried double-checking the permissions of the file, as well as running every command as root, in case permissions were an issue elsewhere.

The base Shadow software is installed properly, as well as tgen. I have run the example experiments with vanilla Shadow and have received good results.

While attempting to reinstall everything from scratch on a new VM, just in case I did something wrong the first time, I get the following error when trying to build libevent:

checking for libevent directory... /home/robert/shadow/shadow-plugin-tor
checking whether we need extra options to link libevent...
configure: error: Found linkable libevent in /home/robert/shadow/shadow-plugin-tor, but it does not seem to run, even with -R. Maybe specify another using --with-libevent-dir}
2020-01-29 03:02:43,480 INFO returning code '-1'

Could these two issues be related? Is there a problem with my pathing syntax? Thanks in advance!

**Comment by robgjansen** [comment]
> [_parser_parseContents] g_markup_parse_context_parse: Shadow XML parsing error 5: attribute 'path': '/home/robert/.shadow/shadow-plugin-tor/build/main/src/tor/libshadow-plugin-tor.so' is not a valid path to an existing regular file

This means that the file is not accessible. So it either is not there, or a permission issue?

If you installed the tor plugin using the included setup script (which you should do if you have not), then the path to the library should be like `/home/rjansen/.shadow/lib/libshadow-plugin-tor.so`. It looks like you are doing something non-standard, because your path looks very different than mine.

I'm pretty sure we set rpath to look in `/home/rjansen/.shadow/lib`, so I recommend trying to install it there using the `python setup install` as shown [on the wiki](https://github.com/shadow/shadow-plugin-tor/wiki#quick-auto-setup). (You should follow the "quick auto setup".)

**Comment by robgjansen** [comment]
Also, please do not use root at any point during the setup or installation. That often causes numerous issues for our users. If you have already done this, then I recommend removing the `~/.shadow` directory and starting over *without using root*.

**Comment by RobertRaduta** [comment]
Started over with a clean VM, and this time the auto setup did not bring up any errors. Thank you very much for the swift reply, I appreciate it!

**Comment by robgjansen** [comment]
Glad you got it working!
